In [2]:
## Numpy

import numpy as np

## Creating array from list

In [ ]:
import numpy as np

arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [2,3,4]])
print("2D array: ", arr_2d)

### List vs numpy

In [ ]:

# py_list = [1,2,3]
# print(py_list * 2)

# np_array = np.array([1,2,3])
# print(np_array * 2)

import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
narray = np.arange(100000) * 2
print("\n array operation time: ", time.time() - start)

### creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((3,4))
print(ones)

full = np.full((2,2), 7)
print(full)

random = np.random.random((2,3))
print(random)

seq = np.arange(0,10,2)
print(seq)

### Vector, Matrix and Tensor

In [13]:
vector = np.array([1,2,3,4])
matrix = np.array([[1,2], [2,3]])
tensor = np.array([[[1,2], [3,4]], [[5,6], [7,8]]]) 
print(tensor.ndim)
print(tensor)

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [12]:
arr = np.array([[1,2,3],
                [4,5,6],
                [9,8,0]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size) #number of elements
print("Data Type: ", arr.dtype)

Shape:  (3, 3)
Dimension:  2
Size:  9
Data Type:  int64


### Array reshaping

In [19]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape((3,4)) # 3,4 dimension
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

# ravel (return view/original array, instead of copy)
raveled = reshaped.ravel()
print(raveled)

#Transpose
trans = reshaped.T
print(trans)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
