## Numpy Array operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8])
print("Slicing: ", arr[2:7])
print("Slicing with step: ", arr[1:8:2])
print("Negative indexing: ", arr[-1])


Slicing:  [3 4 5 6 7]
Slicing with step:  [2 4 6 8]
Negative indexing:  8


In [8]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
print("Specific element: ", arr_2d[1,2]) #1 row 2nd element
print("Entire row: ", arr_2d[1]) #entire row
print("Entire col: ", arr_2d[:, 1])


Specific element:  6
Entire row:  [4 5 6]
Entire col:  [2 5 8]


### Sorting


In [ ]:
unsorted_array = np.array([3,1,4,5,6,7,1])
print(np.sort(unsorted_array))

arr_2d = np.array([[1,2,0], [8,5,6], [7,8,1]]) 
print("Sorted array by column: ", np.sort(arr_2d, axis=0))
print("Sorted array by row: ", np.sort(arr_2d, axis=1))

[1 1 3 4 5 6 7]
Sorted array by column:  [[1 2 0]
 [7 5 1]
 [8 8 6]]
Sorted array by column:  [[0 1 2]
 [5 6 8]
 [1 7 8]]


### Filtering

In [13]:
arr = np.array([1,2,3,4,5,6,7,8])
even_nums = arr[arr % 2 == 0]
print(even_nums)

# Filtering with mask
mask = arr > 5
print("Numbers greater than 5: ", arr[mask])

[2 4 6 8]
Numbers greater than 5:  [6 7 8]
